### ISSUE TITLE
Feature request: manually trigger rerun

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [watchexec/cargo-watch#209] opened 2022-08-04 23:04 UTC
It would be great if it was possible to manually trigger a rerun after the application finishes, for example by hitting `enter` or `control-d` on the application input (`stdin`).

Use case:
My application generates random images. After I am done inspecting one, if it is not to my liking, I want to rerun the entire thing. Currently I do this via `undo-redo-save` in my editor, but that triggers  new a new `cargo check` in the editor and `cargo build` in `cargo watch`, while just rerunning the same binary would be much more efficient.

Note that always rerunning isn't a good option -- that would keep showing the image popup over my editor.

**Comment by passcod** [comment] 2022-08-05 04:11
Duplicate of watchexec/watchexec#67

**Closed by passcod** 2022-08-05 04:11 UTC
