### ISSUE TITLE
Mismatched type errors preventing build

### ISSUE THREAD

**Issue by Sylvanbain** [watchexec/cargo-watch#306] opened 2024-05-12 18:52 UTC
I don't know whether this is the appropriate place but I'm having issues when trying to build it as I was following along the Zero to Production book.

It says there are 2 mismatched type errors in the notify (lib)? 
expected `winapi::ctypes::c_void`, found `libc::c_void` in line 276 of windows.rs 
expected `winapi::ctypes::c_void`, found `libc::c_void` in line 282 of windows.rs

I uploaded screenshots, maybe it can help.
![error1](https://github.com/watchexec/cargo-watch/assets/50839660/df89d478-f55a-43be-9a18-e448479c8a8a)
![error2](https://github.com/watchexec/cargo-watch/assets/50839660/bd99c611-00c2-4ce9-acdd-7ef2eb1d6d58)

**Comment by passcod** [comment] 2024-05-12 22:18
Use `--locked`

Duplicate of #304

**Closed as not planned by passcod** 2024-05-12 22:18 UTC
